# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10
# Mod Properties
mod_version=0.4
maven_group=com.ponuing
archives_base_name=CIT-Reborn
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.119.4+1.21.4
modmenu_version=13.0.3

# Publishing
game_versions_mr=1.21.4
game_versions_curse=1.21.4

prefix=[1.21.4]
release_type=release
changelog_filter=[feat],[fix],[change],[update],[docs],[translations]
mod_name=CIT Reborn
github_owner=ponuing
github_repo=CIT-Reborn
github_url=https://github.com/ponuing/CIT-Reborn
